#!/usr/local/bin/perl -w

# $Id: target,v 1.4 2003/05/16 08:53:56 oradb Exp $
# oracle dbms_debug wrapper
# sqlplus < compile.sql
#
# DEBUG=1 perl590 ./oradb ... keyserver.appinfo\(?,?\) xxx
#
use strict;
use Oracle::Debug;

my $o_debug = Oracle::Debug->new();
$o_debug->target;
exit;

__END__

$|=1;

my $DEBUG = $ENV{DEBUG} || 1;
sub print  { print ('target:   ',@_, "\n") if $DEBUG};

my $o_debug = Oracle::Debug->new();
&print("audid-sid: "  .$o_debug->audit." audited($$)");
$DB::single=2; # 
my $dbid = $o_debug->start_target('rjsf_oracle_dbno');
&print("target dbid: $dbid (started)");
$DB::single=2; # about to free debugger session (if it's attached)
&print('run: '.$o_debug->run("x('xxx')").' ran'); # frees debugger session - or exec from the other side?
# &print('cleaning up: '.target->cleanup.'cleaned up');
exit 0;
